config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  root "payments#index"

  resources :payments do
    member do
      get :payment_pdf
      get :next_step
      get :thankyou
      get :resend
    end
  end
  resources :signatures, only: [:new, :create]
  devise_for :users
end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/payment.rb
class Payment < ActiveRecord::Base
  extend FriendlyId
  friendly_id :customer_name, use: :slugged

  # validation
	validates :amount, :product_name, :customer_name, :address, :city, :state,
            :post_code, :country, :card_number, :phone, :card_expiry,
            :date_of_birth, presence: true
	validates :amount,  numericality: { only_float: true }
  validates :card_number,  numericality: { only_integer: true, max: 4 }
  validates :email, presence: true,
                    :format => { :with => /\A[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]+\z/ ,
                    :message => 'is invalid!'},
                    :on => :create

  # association
  has_one :sign, dependent: :destroy
  belongs_to :user
end

app/models/sign.rb
class Sign < ActiveRecord::Base
  # association
  belongs_to :payment

  # validation
  validates :payment_id, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :rememberable, :trackable, :validatable

  # association
  has_many :payments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  #before_action :authenticate_user!


protected

  ActiveAdmin::ResourceController.class_eval do
    def find_resource
      if resource_class.is_a?(FriendlyId)
        scoped_collection.where(slug: params[:id]).first!
      else
        scoped_collection.where(id: params[:id]).first!
      end
    end
  end

private

  def generated_token
    loop do
      token = SecureRandom.urlsafe_base64(32)
      break token unless Payment.exists?(token: token)
    end
  end
  helper_method :generated_token
end

app/controllers/payments_controller.rb
class PaymentsController < ApplicationController
  before_action :payment, only: [:payment_pdf, :show, :destroy, :next_step, :thankyou]
  before_action :verify_token, only: [:show, :payment_pdf]

  before_filter :authenticate_user!, only: [:index]


  def index
    payments
  end

  def show
    @signature = Sign.new(payment_id: payment.id)
  end

  def new
    @payment = Payment.new
  end

  def create
    @payment = Payment.new(payment_params)
    @payment.token = generated_token
    @payment.ip_address = request.remote_ip
    if @payment.save
      gflash success: "Payments was successfully created."



      # send email with the link to sign the payment
      PaymentMailer.payment_confirmation(@payment).deliver
      redirect_to next_step_payment_path(@payment)
    else
      gflash :now, error: @payment.errors.full_messages.join("<br/>").html_safe
      render :new
    end
  end

  def resend
    @payment = Payment.friendly.find(params[:id])
    PaymentMailer.payment_confirmation(@payment).deliver
    gflash success: "You have successfully resend the confirmation to sign the document to '#{@payment.email}'."
    redirect_to payments_path
  end

  def destroy
    @payment.destroy
    gflash success: 'Payment was successfully destroyed.'
    redirect_to root_path
  end

  def payment_pdf
    render pdf: "#{@payment.product_name}"
  end

  def next_step; end

  def thankyou; end

private

  def payment
    @payment = Payment.friendly.find(params[:id])
  end

  def payments
    if current_user == User.last and !(params[:search].present? or params[:from_date].present?)
      @payments ||= Payment.order(created_at: :desc).page(params[:page])
    elsif params[:search].present?
      @payments = Payment.where("email ILIKE (?) OR customer_name ILIKE (?) OR card_number ILIKE (?)", "%#{params[:search]}%","%#{params[:search]}%","%#{params[:search]}").page(params[:page])
    elsif params[:from_date].present?
      @payments = Payment.where("date(created_at) BETWEEN '#{params[:from_date]}' AND '#{params[:end_date]}'").page(params[:page])
    else
      @payments = []
    end
  end

  def verify_token
    unless payment.token == params[:signature_token]
      gflash error: 'Unauthorized access!!'
      redirect_to root_path
    end
  end

  def payment_params
    params.require(:payment)
          .permit(
              :product_name,
              :customer_name,
              :address,
              :city,
              :state,
              :post_code,
              :country,
              :phone,
              :email,
              :card_number,
              :amount,
              :card_expiry,
              :card_cvv,
              :date_of_birth
          )
  end
end

app/controllers/signatures_controller.rb
class SignaturesController < ApplicationController
  #skip_before_filter :authenticate_user!, only: [:create]

  def create
    @signature = Sign.new(signature_params)

    if @signature.save!
      @signature.payment.update(is_signed: true, token: generated_token)

      # send email with the link to sign the payment
      PaymentMailer.payment_pdf(@signature.payment).deliver

      gflash success: "You have successfully confirm the payment.\n Please check your email"
      redirect_to thankyou_payment_path(@signature.payment)
    else
      gflash error: @signature.errors.full_messages.join("<br />").html_safe
      redirect_to :back
    end
  end

private
  def signature_params
    params.require(:sign).permit(:signature, :payment_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/payments_helper.rb
module PaymentsHelper
end

app/helpers/signatures_helper.rb
module SignaturesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charste='utf-8'>
     <title><%= "BlueArchStore" || @page_title %></title>
    <%= stylesheet_link_tag    'application' %>
    <%= javascript_include_tag 'application' %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <nav class="navbar navbar-default navbar-fixed-top">
      <div class="container-fluid">
        <!-- brand -->
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
        </div>
        <!-- /brand -->

        <!-- right elements -->
          <div class="collapse navbar-collapse" id="registration-navbar">
          <ul  class="nav navbar-nav navbar-left">
            <h2><li><%= link_to "BlueArchStore", "/", :style => 'color: white; position: relative; top: -5px;' %></li></h2>
          </ul>
            <ul class="nav navbar-nav navbar-right">
            <li class="btn-sm"><%= link_to "Contract Form", new_payment_path %></li>
                <li class="btn-sm"><%= current_user ? (link_to "Paymnets", payments_path) : (link_to "Login", new_user_session_path) %></li>
              <li class="btn-sm">
                  <%= current_user ? (link_to "Hello Admin, Logout?", destroy_user_session_path, method: :delete) : '' %>
              </li>
            </ul>
          </div>
          <!-- /right elements -->
      </div>
    </nav>

    <div class="row">
      <%= yield %>
    </div>

    <%= gflash %>
  </body>
</html>
<style>
  .row{
    margin-right: 0;
    margin-left: 0;
  }
  .glyphicon{
    top: 0;
  }
</style>

app/views/payments/_signature.html.erb
<div class="signature-box" id="signature-box">
  <canvas class="pad" width="190" height="70"></canvas>
</div>
<span class="signature-date-placeholder">
  <%= @payment.sign.created_at.utc.strftime("%B %d %Y - %H:%M %p") unless @payment.try(:sign).blank? %>
</span>


<script>
  $(function() {
    var data = <%= @payment.sign.signature.to_json.html_safe %>;
    $("#signature-box").signaturePad({displayOnly: true}).regenerate(data);
  });
</script>

app/views/payments/_signature_form.html.erb
<!-- Modal -->
<div class="modal fade" id="signatureForm" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel">Signature Form</h4>
      </div>
      <%= simple_form_for @signature, url: signatures_path, method: :post do |f| %>
        <div class="modal-body">
          <div class="borderd">
            <canvas class="pad" width="190" height="70"></canvas>
          </div>
          <%= f.hidden_field :signature, class: 'output' %>
          <%= f.hidden_field :payment_id, value: @payment.id %>
        </div>
        <div class="modal-footer">
          <a href="#clear" class="clearButton btn btn-sm btn-default">Clear</a>
          <%= f.submit 'Done', class: 'btn btn-sm btn-primary' %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/payments/index.html.erb
<% @page_title = "Payments" %>
<div class="container" style="width: 1290px;">
<hr />

    <div style="position: relative;">
			<%= form_tag payments_path, method: 'GET' do %>
			  <%= text_field_tag :search,'', placeholder: "#{params[:search] ? params[:search] : 'Search'}", style: "width: 290px; padding: 10px; border: 1px solid lightskyblue; border-radius: 5px;" %>
			  <%= submit_tag "Search", class: 'btn btn-sm btn-primary' %>
			<% end %>
		</div>

		<div style="position: relative;top: -50px;float: right;">
			<%= form_tag payments_path, method: 'GET' do %>
			  <%= text_field_tag :from_date,'', placeholder: "#{params[:from_date] ? params[:from_date] : 'From Date'}", class: 'datepicker', style: "width: 190px; padding: 10px; border: 1px solid lightskyblue; border-radius: 5px;" %>
			  -
			  <%= text_field_tag :end_date,'', placeholder: "#{params[:end_date] ? params[:end_date] : 'End Date'}", class: 'datepicker', style: "width: 190px; padding: 10px; border: 1px solid lightskyblue; border-radius: 5px;" %>
			  <%= submit_tag "Search", class: 'btn btn-sm btn-primary' %>
			<% end %>
		</div>

		<br />
	<div class="panel panel-info">
		<!-- panel heading -->

		<div class="panel-heading clearfix">
			<h4 class="panel-title pull-left" style="padding-top: 7.5px;">
        <strong><%= pluralize Payment.count, "Payment" %></strong>
      </h4>

      <div class="btn-group pull-right" style="right: -440px;">
        <%= link_to "<i class='glyphicon glyphicon-plus'></i> New Payment".html_safe, new_payment_path,  class: 'btn btn-sm btn-primary pull-right' %>
      </div>
		</div>

		<!-- panel body -->
		<div class="panel-body">
			<table class="table table-condensed">
				<thead>
					<tr>
						<th></th>
						<th> CustomerName </th>
						<th> amount </th>
						<th> ProductName </th>
						<th> Address</th>
						<th> Phone</th>
						<th> Email</th>
						<th> CardNumber </th>
						<th></th>
						<th></th>
					</tr>
				</thead>

				<tbody>
					<% @payments.each do |payment| %>
						<tr>
							<td>
								<span class="glyphicon glyphicon-<%= payment.is_signed ? 'ok text-success' : 'remove text-danger' %>"></span>
							</td>
							<td><%= payment.customer_name %></td>
							<td><%= number_to_currency(payment.amount) %></td>
							<td><%= payment.product_name %></td>
							<td><%= payment.address %></td>
							<td><%= payment.phone %></td>
							<td><%= payment.email %> </td>
							<td>***<%= payment.card_number[-4..-1] %> </td>
							<td>
							 <% if payment.is_signed && payment.try(:sign).present? %>
								<%= link_to "<i class='glyphicon glyphicon-save'></i>".html_safe, payment_pdf_payment_path(payment, signature_token: payment.token), class: 'btn btn-xs btn-primary', target: "_blank"  %>
								<% else %>
								  <%= link_to "<i class='glyphicon glyphicon-send'></i>".html_safe, resend_payment_path(payment), class: 'btn btn-xs btn-danger' %>
								<% end %>
							</td>
							<td>
								<%= link_to "<i class='glyphicon glyphicon-trash'".html_safe, payment_path(payment), method: :delete, data: { confirm: 'Are you sure want to delete?' }, class: 'btn btn-xs btn-danger' %>
							</td>
						</tr>
					<%end%>
				</tbody>
			</table>
		</div>
		<div class="panel-footer">
			<%= paginate @payments, theme: 'twitter-bootstrap-3' %>
		</div>
	</div>
</div>

app/views/payments/new.html.erb
<% @page_title = "Payment" %>

<div class="col-md-6 col-md-offset-3">
  <div class="panel panel-info">
    <div class="panel-heading">
      <h4>Contract Agreement with BlueArch Store</h4>
    </div>

    <%= simple_form_for @payment do |f| %>
      <div class="panel-body">
        <div class="input-group">
          <span class="input-group-addon glyphicon glyphicon-shopping-usd">$</span>
          <%= f.input :amount, placeholder: "amount", class: "form-control input-lg", label: false %>
          <span class="input-group-addon">.00</span>
        </div><br/>

        <div class="input-group">
          <span class="input-group-addon glyphicon glyphicon-shopping-cart"></span>
          <%= f.input :product_name, placeholder: "ProductName", class: "form-control input-lg", label: false %>
        </div><br/>

        <div class="input-group">
          <span class="input-group-addon glyphicon glyphicon-user"></span>
          <%= f.input :customer_name, placeholder: "Customer Name", class: "form-control input-lg", label: false %>
        </div><br/>

        <div class="input-group">
          <span class="input-group-addon glyphicon glyphicon-calendar"></span>
          <%= f.input :date_of_birth, as: :string, input_html: { class: "datepicker" }, placeholder: "Date of Birth", class: "form-control input-lg", label: false %>
        </div><br/>

        <div class="input-group">
          <span class="input-group-addon glyphicon glyphicon-home"></span>
          <%= f.input :address, placeholder: "Address", class: "form-control input-lg", label: false %>
        </div><br/>

        <div class="input-group">
          <span class="input-group-addon glyphicon glyphicon-road"></span>
          <%= f.input :city, placeholder: "City", class: "form-control input-lg", label: false %>
        </div><br/>

        <div class="input-group">
          <span class="input-group-addon glyphicon glyphicon-globe"></span>
          <%= f.input :state, placeholder: "State", class: "form-control input-lg", label: false %>
        </div><br/>

        <div class="input-group">
          <span class="input-group-addon glyphicon glyphicon-globe"></span>
          <%= f.input :post_code, placeholder: "Postcode", class: "form-control input-lg", label: false %>
        </div><br/>

        <div class="input-group">
          <span class="input-group-addon glyphicon glyphicon-flag"></span>
          <%= f.input :country, placeholder: "Country", class: "form-control input-lg", label: false, prompt: "Select Country" %>
        </div><br/>

        <div class="input-group">
          <span class="input-group-addon glyphicon glyphicon-phone"></span>
          <%= f.input :phone, placeholder: "Phone", class: "form-control input-lg", label: false %>
        </div><br/>

        <div class="input-group">
          <span class="input-group-addon glyphicon glyphicon-envelope"></span>
          <%= f.input :email, placeholder: "Email", class: "form-control input-lg", label: false %>
        </div><br/>

        <div class="input-group">
          <span class="input-group-addon glyphicon glyphicon-credit-card"></span>
          <%= f.input :card_number, placeholder: "enter your last 4 digit of card", class: "form-control input-lg", label: false %>
        </div><br/>

        <div class="input-group">
          <span class="input-group-addon glyphicon glyphicon-calendar"></span>
          <%= f.input :card_expiry, placeholder: "CardExpiry", class: "form-control input-lg", label: false %>
        </div><br/>
      </div>

      <div class="panel-footer">
        <%= f.submit "Submit", class: 'btn btn-sm btn-primary' %>
        <% if current_user %>
          <%= link_to 'View All Payments', payments_path, class: 'btn btn-sm btn-default pull-right' %>
        <% end %>
      </div>
    <%end%>
  </article>
</section>

app/views/payments/next_step.html.erb
<div class="row">
  <div class="container">
    <div class="col-xs-12 col-sm-10 right-pannel">
      <!-- <img src="/assets/croped-img.png" class="img-border" width="100%" height="100%" /> -->
      <div class="panel panel-info panel-pdf">
        <!-- panel heading -->
        <div class="panel-heading">
          <h3 class="panel-title">
            Thankyou for your payment information
          </h3>
        </div>

        <div class="panel-body">
          <p>Hi <%= @payment.customer_name %>,</p>

          <p>Thankyou for your payment information. You should be able to get 'Please confirm payment and sign it' email shortly in your <%= @payment.email %> email. Your next step is to confirm and sign that document.<br/>

          <p>The email will delivery shortly, however if you didn't received email after some time, you can contact our support team.</p>
        </div>

        <div class="panel-footer">
          <address>
            Thanks, <br/>
            Blue Arch Store Support <br/>
            <a href="mailto:service.bluearchstore@gmail.com?subject=feedback">service.bluearchstore@gmail.com</a>
          </address>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/payments/show.html.erb
 <div class="row">
  <div class="container">
    <!-- in future if we required drag and drop functionality enable it -->
    <!-- <div class="col-xs-12 col-sm-2 left-pannel affix">
      <h4>Common</h4>
      <hr>
      <input type="button" class="btn btn-info" value="Signature">
      <p class=""></p>
    </div> -->

    <div class="col-xs-12 col-sm-10 right-pannel">
      <!-- <img src="/assets/croped-img.png" class="img-border" width="100%" height="100%" /> -->
      <div class="panel panel-info panel-pdf">
        <!-- panel heading -->
        <div class="panel-heading">
          <h3 class="panel-title">
            Verify & Place Signature
          </h3>
        </div>

        <!-- panel body -->
        <div class="panel-body">
          <div class="row">
            <div class=" col-md-12 col-lg-12 ">
              <table class="table table-user-information">
                <tbody>
                  <tr>
                    <td>Verified</td>
                    <td>
                      <span class="glyphicon glyphicon-<%= @payment.is_signed ? "ok text-success" : "remove text-danger" %>"></span>
                    </td>
                  </tr>
                  <tr>
                    <td>Customer Name</td>
                    <td><%= @payment.customer_name %></td>
                  </tr>
                  <tr>
                    <td>Date of birth</td>
                      <td><%= @payment.date_of_birth %></td>
                    </tr>
                  <tr>
                    <td>Customer Email</td>
                    <td><%= @payment.email %></td>
                  </tr>
                  <tr>
                    <td>Amount</td>
                    <td><%= number_to_currency @payment.amount %></td>
                  </tr>
                  <tr>
                    <td>Product Name</td>
                    <td><%= @payment.product_name %></td>
                  </tr>
                  <tr>
                    <td>Address</td>
                    <td><%= @payment.address %></td>
                  </tr>
                    <td>City</td>
                    <td><%= @payment.city %></td>
                  </tr>
                    <td>State</td>
                    <td><%= @payment.state %></td>
                  </tr>
                  <tr>
                    <td>Postal Code</td>
                    <td><%= @payment.post_code %></td>
                  </tr>
                    <td>Country</td>
                    <td><%= @payment.country %></td>
                  </tr>
                  </tr>
                    <td>Phone</td>
                    <td><%= @payment.phone %></td>
                  </tr>
                  </tr>
                    <td>Card Number:</td>
                    <td>
                      <%= @payment.card_number %>
                    </td>
                  </tr>
                  <tr>
                    <td>Card Expiry</td>
                    <td><%= @payment.card_expiry%></td>
                  </tr>
                  <tr>
                    <td colspan="2">
                      <p class="text-info">I agree to the T&C/Policies of the Company and I am satisfied with the service</p>
                    </td>
                  </tr>
                </tbody>
              </table>
            </div>
          </div>
        </div>

        <!-- panel footer -->
        <div class="panel-footer clearfix">
          <div class="signature-wrapper">
            <% if @payment.is_signed && @payment.sign.present? %>
              <%= render 'signature' %>
            <% else %>
              <div class="btn btn-sm btn-primary" data-toggle="modal" data-target="#signatureForm">click here to sign</div>
            <% end %>
          </div>
        </div>

        <%= render 'signature_form' %>

      </div>
    </div>
  </div>
</div>

app/views/payments/thankyou.html.erb
<div class="row">
  <div class="container">
    <div class="col-xs-12 col-sm-10 right-pannel">
      <!-- <img src="/assets/croped-img.png" class="img-border" width="100%" height="100%" /> -->
      <div class="panel panel-info panel-pdf">
        <!-- panel heading -->
        <div class="panel-heading">
          <h3 class="panel-title">
            Thankyou For confirming your payment
          </h3>
        </div>

        <div class="panel-body">
          <p>Hi <%= @payment.customer_name %>,</p>

          <p>Thankyou for confirming your payment. You should be able to get thankyou email shortly in your <%= @payment.email %> email.<br/>
          We have sent you a copy of PDF document of your payment slip and your signature on it.</p>

          <p>The email will delivery shortly, however if you didn't received email after some time, you can contact our support team.</p>
        </div>

        <div class="panel-footer">
          <address>
            Thanks, <br/>
            Blue Arch Store Support <br/>
            <a href="mailto:service.bluearchstore@gmail.com?subject=feedback">service.bluearchstore@gmail.com</a>
          </address>
        </div>
      </div>
    </div>
  </div>
</div>